#! /bin/bash
app=csleditor

#retrieve arguments
domain=$(sudo yunohost app setting $app domain)
path=$(sudo yunohost app setting $app path)
is_public=$(sudo yunohost app setting $app is_public)

# Remove trailing "/" for next commands
path=${path%/}

# Copy source files
final_path=/var/www/$app
sudo mkdir -p $final_path
sudo git clone --recursive https://github.com/citation-style-editor/csl-editor-demo-site.git csl-demo
sudo ./csl-demo/deploy.sh $final_path

#configure nginx settings
sed -i "s@YNH_WWW_PATH@$path@g" ../conf/nginx.conf
sed -i "s@YNH_WWW_ALIAS@$final_path/@g" ../conf/nginx.conf
sudo cp ../conf/nginx.conf /etc/nginx/conf.d/$domain.d/$app.conf

# If app is public, add url to SSOWat conf as skipped_uris
if [ "$is_public" = "Yes" ];
then
	sudo yunohost app setting $app unprotected_uris -v "/"
fi

# Restart services
sudo service nginx reload
sudo yunohost app ssowatconf